
  #Configuração de Conexão com Banco de Dados

spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: XX
    password: XX



  #Configuração de Mapeamento Objeto Relacional
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false

