
  #Configuração de Conexão com Banco de Dados

spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: pf1646
    password: fiap23



  #Configuração de Mapeamento Objeto Relacional
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

